sequenceDiagram
    actor A as Admin / HRD
    participant FP as FormPengumuman
    participant PC as PengumumanController
    participant DP as DataPengumuman

    A->>FP: Input Judul, Isi & Klik Publish()
    FP->>PC: SubmitPengumuman()
    PC->>DP: InsertPengumumanBaru()
    DP-->>PC: Return: Pengumuman Tersimpan
    PC-->>FP: Tampilkan Alert Sukses()
